### ISSUE TITLE
IOError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by sunningboy** [aritter/twitter_nlp#14]
OS is mac air OX.
How can solve it?
----------
$ cat test.1k.txt | python python/ner/extractEntities2.py 
/bin/sh: .//python/cap/cap_classify: cannot execute binary file
Traceback (most recent call last):
  File "python/ner/extractEntities2.py", line 131, in <module>
    goodCap = capClassifier.Classify(words) > 0.9
  File ".//python/cap/cap_classifier.py", line 33, in Classify
    self.capClassifier.stdin.write("%s\n" % self.fe.Extract(' '.join(words)))
IOError: [Errno 32] Broken pipe

**Comment by mdtareque** [comment]
Even on Ubuntu 15.10 

    $ cat test.1k.txt | python python/ner/extractEntities2.py 
    .//python/cap/cap_classify: 1: .//python/cap/cap_classify: Syntax error: ")" unexpected
    Traceback (most recent call last):
      File "python/ner/extractEntities2.py", line 131, in <module>
        goodCap = capClassifier.Classify(words) > 0.9
      File ".//python/cap/cap_classifier.py", line 33, in Classify
        self.capClassifier.stdin.write("%s\n" % self.fe.Extract(' '.join(words)))
    IOError: [Errno 32] Broken pipe

**Comment by sruteesh** [comment]
Any solutions??
Have the same issue

**Comment by aritter** [comment]
Maybe try running build.sh

-Alan

**Comment by napsternxg** [comment]
@sruteesh can you try using my branch mentioned in Pull request #16

**Comment by sruteesh** [comment]
Hi @napsternxg  and @aritter 
Thanks for the prompt response. But the issue still seems to be there. I'm still getting the same error. I tried trying it out on my friend's laptop. Same issue.

`$ python python/ner/extractEntities.py test.1k.txt
Starting with the following configuration
----------------------------------------
Input file: test.1k.txt
Text Position: 0
Output file: None
Chunk: False
POS: False
Event: False
Classify: False
Mallet Memory: 256m
----------------------------------------
No output file given. Will write to STDOUT.
Error: Could not find or load main class cc.mallet.fst.SimpleTaggerStdin
/bin/sh: .//python/cap/cap_classify: cannot execute binary file: Exec format error
Finished loading all models. Now reading from test.1k.txt and writing to None
Traceback (most recent call last):
  File "python/ner/extractEntities.py", line 167, in <module>
    goodCap = capClassifier.Classify(words) > 0.9
  File ".//python/cap/cap_classifier.py", line 33, in Classify
    self.capClassifier.stdin.write("%s\n" % self.fe.Extract(' '.join(words)))
IOError: [Errno 32] Broken pipe
`
Please look into the matter.

**Comment by chandra589** [comment]
@napsternxg and @aritter 
I'm getting the same error as @sruteesh is having.
Can you please look into it.

**Comment by napsternxg** [comment]
@sruteesh @chandra589 
I tried it just now on my machine. It works fine. Can you give details about your system ?

**Comment by sruteesh** [comment]
@napsternxg I am using pyhton 3.4 and running it on Cygwinx64 terminal from windows 10.

**Comment by napsternxg** [comment]
I think this code is compatible with only Python 2.7 because of the print statement formats. Try with Python 2.7.

**Comment by sidewallme** [comment]
I have the same issue. Any solutions?

**Comment by joanaz** [comment]
I'm having the same issue. I got an error when running the build.sh:
```
warning: optimization level '-O9' is not supported; using '-O3' instead
In file included from param.cpp:28:
In file included from ./common.h:76:
./getopt.h:131:12: error: conflicting types for 'getopt'
extern int getopt ();
           ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/unistd.h:508:6: note: 
      previous declaration is here
int      getopt(int, char * const [], const char *) __DARWIN_ALIAS(getopt);
         ^
param.cpp:217:17: warning: conversion from string literal to 'char *' is
      deprecated [-Wc++11-compat-deprecated-writable-strings]
    char *tmp = "TinySVM::Param::set";
                ^
2 warnings and 1 error generated.
make[2]: *** [param.lo] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive-am] Error 2
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
I'm using python 2.7.

**Comment by rksaxena** [comment]
Anybody got a solution? Facing the same issue

**Comment by VikoTse** [comment]
I have the same issue

`
Starting with the following configuration
----------------------------------------
Input file: test.1k.txt
Text Position: 0
Output file: output.txt
Chunk: False
POS: False
Event: False
Classify: False
Mallet Memory: 256m
----------------------------------------
/bin/sh: 1: java: not found
Finished loading all models. Now reading from test.1k.txt and writing to output.txt
Traceback (most recent call last):
  File "python/ner/extractEntities.py", line 197, in <module>
    ner.stdin.write(("\t".join(seq_features) + "\n").encode('utf8'))
IOError: [Errno 32] Broken pipe
`

When I running build.sh
`bash: ./build.sh: Permission denied
`

My python version: 2.7.12

**Comment by DerekZH** [comment]
same issue here, python version is Python 2.7.10.  Would be great to see a fix.

**Comment by DaehanKim** [comment]
I have some similar issue. 

```
Anonymous:~/twitter_nlp$ python python/ner/extractEntities.py test.1k.txt -o output.txtStarting with the following configuration
----------------------------------------
Input file: test.1k.txt
Text Position: 0
Output file: output.txt
Chunk: False
POS: False
Event: False
Classify: False
Mallet Memory: 256m
----------------------------------------
/bin/sh: 1: java: not found
Finished loading all models. Now reading from test.1k.txt and writing to output.txt
Traceback (most recent call last):
  File "python/ner/extractEntities.py", line 197, in <module>
    ner.stdin.write(("\t".join(seq_features) + "\n").encode('utf8'))
IOError: [Errno 32] Broken pipe
```

And I found out that running ```./build.sh``` cause some errors like :

```
LabeledLDA_infer_stdin.c: In function 'main':
LabeledLDA_infer_stdin.c:693:10: warning: implicit declaration of function 'time' [-Wimplicit-function-declaration]
   setall(time(0),time(0));   /* initialize random number generator */
          ^
TinySVM-0.09/
TinySVM-0.09/README
TinySVM-0.09/stamp-h.in
TinySVM-0.09/AUTHORS
TinySVM-0.09/COPYING
TinySVM-0.09/ChangeLog
TinySVM-0.09/INSTALL
TinySVM-0.09/Makefile.am
TinySVM-0.09/Makefile.in
TinySVM-0.09/NEWS
TinySVM-0.09/THANKS
TinySVM-0.09/acconfig.h
TinySVM-0.09/aclocal.m4
TinySVM-0.09/config.guess
TinySVM-0.09/config.h.in
TinySVM-0.09/config.sub
TinySVM-0.09/configure
TinySVM-0.09/configure.in
TinySVM-0.09/install-sh
TinySVM-0.09/ltconfig
TinySVM-0.09/ltmain.sh
TinySVM-0.09/missing
TinySVM-0.09/mkinstalldirs
TinySVM-0.09/tinysvm.spec.in
TinySVM-0.09/tinysvm.spec
TinySVM-0.09/src/
TinySVM-0.09/src/Makefile.am
TinySVM-0.09/src/Makefile.bcc32.in
TinySVM-0.09/src/Makefile.in
TinySVM-0.09/src/Makefile.msvc.in
TinySVM-0.09/src/getopt.c
TinySVM-0.09/src/getopt1.c
TinySVM-0.09/src/getopt.h
TinySVM-0.09/src/common.h
TinySVM-0.09/src/param.cpp
TinySVM-0.09/src/param.h
TinySVM-0.09/src/kernel.h
TinySVM-0.09/src/classifier.h
TinySVM-0.09/src/classifier.cpp
TinySVM-0.09/src/q_matrix.h
TinySVM-0.09/src/q_matrix.cpp
TinySVM-0.09/src/cache.h
TinySVM-0.09/src/timer.h
TinySVM-0.09/src/base_example.cpp
TinySVM-0.09/src/base_example.h
TinySVM-0.09/src/example.cpp
TinySVM-0.09/src/example.h
TinySVM-0.09/src/model.cpp
TinySVM-0.09/src/model.h
TinySVM-0.09/src/base_solver.h
TinySVM-0.09/src/oneclass_solver.cpp
TinySVM-0.09/src/oneclass_solver.h
TinySVM-0.09/src/svm_solver.cpp
TinySVM-0.09/src/svm_solver.h
TinySVM-0.09/src/svr_solver.cpp
TinySVM-0.09/src/svr_solver.h
TinySVM-0.09/src/qp_solver.h
TinySVM-0.09/src/qp_solver.cpp
TinySVM-0.09/src/tinysvm.h
TinySVM-0.09/src/svm_learn.cpp
TinySVM-0.09/src/svm_classify.cpp
TinySVM-0.09/src/svm_model.cpp
TinySVM-0.09/src/misc.h
TinySVM-0.09/tests/
TinySVM-0.09/tests/Makefile.am
TinySVM-0.09/tests/Makefile.in
TinySVM-0.09/tests/test.sh
TinySVM-0.09/tests/test2.sh
TinySVM-0.09/tests/test3.sh
TinySVM-0.09/tests/test4.sh
TinySVM-0.09/tests/test5.sh
TinySVM-0.09/tests/train.svmdata
TinySVM-0.09/tests/train.svrdata
TinySVM-0.09/tests/test.svmdata
TinySVM-0.09/man/
TinySVM-0.09/man/Makefile.in
TinySVM-0.09/man/Makefile.am
TinySVM-0.09/man/svm_learn.1
TinySVM-0.09/man/svm_classify.1
TinySVM-0.09/man/svm_model.1
TinySVM-0.09/doc/
TinySVM-0.09/doc/Makefile.in
TinySVM-0.09/doc/Makefile.am
TinySVM-0.09/doc/svm_learn.html
TinySVM-0.09/doc/svm_classify.html
TinySVM-0.09/doc/svm_model.html
TinySVM-0.09/doc/index.html
TinySVM-0.09/doc/tinysvm.css
TinySVM-0.09/doc/doc/
TinySVM-0.09/doc/doc/Makefile.in
TinySVM-0.09/doc/doc/Makefile.am
TinySVM-0.09/doc/doc/index.html
TinySVM-0.09/doc/doc/libtinysvm.html
TinySVM-0.09/doc/doc/tinysvm.css
TinySVM-0.09/doc/doc/Makefile
TinySVM-0.09/doc/doc/svm_learn.html
TinySVM-0.09/doc/doc/svm_classify.html
TinySVM-0.09/doc/doc/svm_model.html
TinySVM-0.09/perl/
TinySVM-0.09/perl/example/
TinySVM-0.09/perl/example/model
TinySVM-0.09/perl/example/svm_classify.pl
TinySVM-0.09/perl/example/svm_learn.pl
TinySVM-0.09/perl/example/hoge
TinySVM-0.09/perl/Makefile.PL.in
TinySVM-0.09/perl/README
TinySVM-0.09/perl/TinySVM.pm
TinySVM-0.09/perl/TinySVM_wrap.c
TinySVM-0.09/ruby/
TinySVM-0.09/ruby/test.rb
TinySVM-0.09/ruby/README
TinySVM-0.09/ruby/TinySVM_wrap.cc
TinySVM-0.09/ruby/extconf.rb.in
TinySVM-0.09/ruby/mkmf.log
TinySVM-0.09/python/
TinySVM-0.09/python/Makefile.pre.in
TinySVM-0.09/python/README
TinySVM-0.09/python/Setup.in
TinySVM-0.09/python/TinySVM.py
TinySVM-0.09/python/TinySVM_wrap.c
TinySVM-0.09/python/install-sh
TinySVM-0.09/python/makesetup
TinySVM-0.09/python/test.py
TinySVM-0.09/java/
TinySVM-0.09/java/BaseExample.java
TinySVM-0.09/java/Example.java
TinySVM-0.09/java/Makefile.in
TinySVM-0.09/java/Model.java
TinySVM-0.09/java/README
TinySVM-0.09/java/TinySVM.java
TinySVM-0.09/java/TinySVM_wrap.c
TinySVM-0.09/java/test.java
creating cache ./config.cache
checking for a BSD compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking whether make sets ${MAKE}... yes
checking for working aclocal... missing
checking for working autoconf... missing
checking for working automake... missing
checking for working autoheader... missing
checking for working makeinfo... missing
checking for gcc... gcc
checking whether the C compiler (gcc  ) works... yes
checking whether the C compiler (gcc  ) is a cross-compiler... no
checking whether we are using GNU C... yes
checking whether gcc accepts -g... yes
checking for c++... c++
checking whether the C++ compiler (c++  ) works... yes
checking whether the C++ compiler (c++  ) is a cross-compiler... no
checking whether we are using GNU C++... yes
checking whether c++ accepts -g... yes
checking how to run the C preprocessor... gcc -E
checking whether gcc needs -traditional... no
checking whether make sets ${MAKE}... (cached) yes
checking host system type... x86_64-unknown-linux-gnu
checking for Cygwin environment... no
checking for mingw32 environment... no
checking build system type... x86_64-unknown-linux-gnu
checking for ld used by GCC... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognise dependant libraries... file_magic ELF [0-9][0-9]*-bit [LM]SB (shared object|dynamic lib )
checking for object suffix... o
checking for executable suffix... no
checking command to parse /usr/bin/nm -B output... ok
checking for dlfcn.h... yes
checking for file... /usr/bin/file
checking for ranlib... ranlib
checking for strip... strip
checking for objdir... .libs
checking for gcc option to produce PIC... -fPIC
checking if gcc PIC flag -fPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.lo... yes
checking if gcc supports -fno-rtti -fno-exceptions... yes
checking whether the linker (/usr/bin/ld) supports shared libraries... yes
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking dynamic linker characteristics... GNU/Linux ld.so
checking if libtool supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
creating libtool
checking for strerror in -lcposix... no
checking how to run the C++ preprocessor... c++ -E
checking for ANSI C header files... no
checking for stdio.h... yes
checking for string.h... yes
checking for math.h... yes
checking for stdlib.h... yes
checking for unistd.h... yes
checking for ctype.h... yes
checking for getopt.h... yes
checking for sys/types.h... yes
checking for sys/times.h... yes
checking for windows.h... no
checking for pid_t... yes
checking for size_t... yes
checking for pow in -lm... yes
checking for exp in -lm... yes
checking for isspace... yes
checking for getopt... yes
checking for getopt_long... yes
checking for memset... yes
checking for bzero... yes
checking for memcpy... yes
checking for bcopy... yes
checking whether make is GNU Make... yes
checking if c++ supports template <class T> (required)... yes
checking if c++ supports const_cast<> (required)... yes
checking if c++ supports static_cast<> (required)... yes
checking if c++ supports dynamic_cast<> (required)... yes
checking if c++ supports bool (required)... yes
checking if c++ supports namespaces (required) ... yes
checking if c++ uses std namespace ... yes
checking if c++ environment provides all required features... yes
checking for java... no
checking for javac... no
checking for jar... no
checking for java include file jni.h... updating cache ./config.cache
creating ./config.status
creating Makefile
creating src/Makefile
creating src/Makefile.bcc32
creating src/Makefile.msvc
creating tests/Makefile
creating man/Makefile
creating doc/Makefile
creating java/Makefile
creating python/Setup
creating perl/Makefile.PL
creating ruby/extconf.rb
creating tinysvm.spec
creating config.h
make  all-recursive
make[1]: Entering directory '/home/daehan/twitter_nlp/TinySVM-0.09'
Making all in src
make[2]: Entering directory '/home/daehan/twitter_nlp/TinySVM-0.09/src'
/bin/sh ../libtool --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt.c
mkdir .libs
gcc -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt.c  -fPIC -DPIC -o .libs/getopt.lo
gcc -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt.c -o getopt.o >/dev/null 2>&1
mv -f .libs/getopt.lo getopt.lo
/bin/sh ../libtool --mode=compile gcc -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt1.c
rm -f .libs/getopt1.lo
gcc -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt1.c  -fPIC -DPIC -o .libs/getopt1.lo
gcc -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c getopt1.c -o getopt1.o >/dev/null 2>&1
mv -f .libs/getopt1.lo getopt1.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c param.cpp
rm -f .libs/param.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c param.cpp  -fPIC -DPIC -o .libs/param.lo
param.cpp: In member function 'int TinySVM::Param::set(const char*)':
param.cpp:217:17: warning: deprecated conversion from string constant to 'char*' [-Wwrite-strings]
     char *tmp = "TinySVM::Param::set";
                 ^
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c param.cpp -o param.o >/dev/null 2>&1
mv -f .libs/param.lo param.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c classifier.cpp
rm -f .libs/classifier.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c classifier.cpp  -fPIC -DPIC -o .libs/classifier.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c classifier.cpp -o classifier.o >/dev/null 2>&1
mv -f .libs/classifier.lo classifier.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c q_matrix.cpp
rm -f .libs/q_matrix.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c q_matrix.cpp  -fPIC -DPIC -o .libs/q_matrix.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c q_matrix.cpp -o q_matrix.o >/dev/null 2>&1
mv -f .libs/q_matrix.lo q_matrix.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c base_example.cpp
rm -f .libs/base_example.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c base_example.cpp  -fPIC -DPIC -o .libs/base_example.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c base_example.cpp -o base_example.o >/dev/null 2>&1
mv -f .libs/base_example.lo base_example.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c example.cpp
rm -f .libs/example.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c example.cpp  -fPIC -DPIC -o .libs/example.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c example.cpp -o example.o >/dev/null 2>&1
mv -f .libs/example.lo example.lo
/bin/sh ../libtool --mode=compile c++ -DHAVE_CONFIG_H -I. -I. -I..     -Wall -O9 -funroll-all-loops -finline -ffast-math -c model.cpp
rm -f .libs/model.lo
c++ -DHAVE_CONFIG_H -I. -I. -I.. -Wall -O9 -funroll-all-loops -finline -ffast-math -c model.cpp  -fPIC -DPIC -o .libs/model.lo
model.cpp: In member function 'virtual int TinySVM::Model::read(const char*, const char*, int)':
model.cpp:230:57: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%s Version %s%*[^\n]\n", tmpbuf, version);
                                                         ^
model.cpp:231:50: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%d%*[^\n]\n",  &param.kernel_type);
                                                  ^
model.cpp:232:45: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%d%*[^\n]\n",  &param.degree);
                                             ^
model.cpp:233:46: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%lf%*[^\n]\n", &param.param_g);
                                              ^
model.cpp:234:46: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%lf%*[^\n]\n", &param.param_s);
                                              ^
model.cpp:235:46: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%lf%*[^\n]\n", &param.param_r);
                                              ^
model.cpp:236:38: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%s%*[^\n]\n",  tmpbuf);
                                      ^
model.cpp:249:34: warning: ignoring return value of 'int fscanf(FILE*, const char*, ...)', declared with attribute warn_unused_result [-Wunused-result]
   fscanf (fp, "%lf%*[^\n]\n", &b);
                                  ^
```

**Comment by jamestch** [comment]
I hava met the similar problem, has anyone get a solution?
when I run "python python/ner/extractEntities.py test.1k.txt -o output.txt", it got an exception as below:
Starting with the following configuration
----------------------------------------
Input file: test.1k.txt
Text Position: 0
Output file: output.txt
Chunk: False
POS: False
Event: False
Classify: False
Mallet Memory: 256m
----------------------------------------
Exception in thread "main" java.lang.NoClassDefFoundError: bsh/Interpreter
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at cc.mallet.util.CommandOption.<init>(CommandOption.java:62)
	at cc.mallet.util.CommandOption$Double.<init>(CommandOption.java:483)
	at cc.mallet.fst.SimpleTaggerStdin.<clinit>(SimpleTaggerStdin.java:173)
Caused by: java.lang.ClassNotFoundException: bsh.Interpreter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 15 more
Finished loading all models. Now reading from test.1k.txt and writing to output.txt
Traceback (most recent call last):
  File "python/ner/extractEntities.py", line 197, in <module>
    ner.stdin.write(("\t".join(seq_features) + "\n").encode('utf8'))
IOError: [Errno 32] Broken pipe

**Comment by Johnsonxiong** [comment]
Hey, guys, good news for Mac users!

I ended up being able to build on Mac (10.7.5) by doing the following:

Download TinySVM and unzip it to the folder of twitter_nlp-master:
https://github.com/shogo82148/TinySVM

Change build.sh in twitter_nlp-master as below:
cd hbc/models
gcc -O3 labels.c stats.c samplib.c LabeledLDA_infer_stdin.c -o LabeledLDA_infer_stdin.out -lm
cd ../../TinySVM
./configure --prefix=`pwd`/../ && make && make install
cd ../python/cap
./build.sh


Then run 
$ ./build.sh
$ export TWITTER_NLP=./
$ cat test.1k.txt | python2 python/ner/extractEntities2.py

This works!
Below is part of the result:
@Jessica_Chobot/O did/O you/O see/O the/O yakuza/B-ENTITY vs/O zombies/O ..../O smh/O but/O cool/O at/O the/O same/O time/O
RT/O @daviddesrosiers/O :/O Happy/O birthday/O @chuckcomeau/O !/O have/O fun/O in/O vancouver/B-ENTITY tonight/O !/O
Spotted/O :/O Kanye/B-ENTITY West/I-ENTITY Celebrates/O LAMB/B-ENTITY With/O Gwen/B-ENTITY Stefani/I-ENTITY :/O New/B-ENTITY York/I-ENTITY Fashion/I-ENTITY Week/I-ENTITY is/O coming/O to/O a/O close/O ,/O but/O not/O before/O .../O http://bit.ly/cSyZUi/O
@zeeDOTi/O i/O might/O join/O in/O if/O I/O make/O it/O home/O in/O time/O ./O :)/O

Hope this helps.

**Comment by vrnmthr** [comment]
@Johnsonxiong worked for me -- thanks! maybe someone can create a PR for this

**Comment by chandrasg** [comment]
TinySVM no longer has `configure` file it seems:
https://github.com/shogo82148/TinySVM
