### ISSUE TITLE
Python 3 compatible?

### ISSUE THREAD

**Issue by ianbstewart** [aritter/twitter_nlp#24]
Hello,

I've tried running `extractEntities.py` with Python 3 and I get the following error:

```
Traceback (most recent call last):
  File "twitter_nlp/python/ner/extractEntities.py", line 28, in <module>
    import Features
  File "twitter_nlp/python/ner/Features.py", line 12, in <module>
    if os.environ.has_key('TWITTER_NLP'):
AttributeError: '_Environ' object has no attribute 'has_key'
```

Is the package compatible with Python 3?

**Comment by Evarln** [comment]
change "if os.environ.has_key('TWITTER_NLP')" by "if ('TWITTER_NLP) in os.environ:"
